GoTravelABit2/Models/TripItem.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTravelABit2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TripItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TripItem()
        {
            this.Files = new HashSet<File>();
        }
    
        public int Id { get; set; }
        public int TripId { get; set; }
        public int Nr { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Date { get; set; }

        public Nullable<decimal> Prize { get; set; }
        public int Type { get; set; }
        public Nullable<int> Wessel { get; set; }
        public string Location { get; set; }
        public string ToLocation { get; set; }
        public string Hotel { get; set; }
        public int Duration { get; set; }
        public string Name { get; set; }
        public string Desscription { get; set; }
        public string Comment { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> CheckInDate { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> CheckOutDate { get; set; }

        [DisplayFormat(DataFormatString = "{0:HH:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> StartTime { get; set; }
    
        public virtual Trip Trip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> Files { get; set; }
    }
}

GoTravelABit2/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GoTravelABit2.Models;

namespace GoTravelABit2.Controllers
{
    public class FilesController : Controller
    {
        private ReisidEntities db = new ReisidEntities();

        public ActionResult Content(int? id)
        {
            if (id.HasValue)
            {
                File file = db.Files.Find(id.Value);
                if (file != null)
                {
                    return File(file.Content, file.ContentType);
                }
            }
            return HttpNotFound();

        }

        public ActionResult Index()
        {
            return View(db.Files.ToList()); 
        }
        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GoTravelABit2/Controllers/TripItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;
using GoTravelABit2.Models;
using System.Globalization;
using System.Net.Http;
using Newtonsoft.Json;
using System.IO;
using System.ComponentModel.DataAnnotations;
using System.Text;
using System.Linq.Expressions;


//namespace GoTravelABit2.Models
//{
//    public static class HtmlHelpers
//    {
//        public static MvcHtmlString DisplayFor<TModel, TValue>(this HtmlHelper<TModel>helper, Expression<Func<TModel, TValue>> expression)
//        {
//            StringBuilder html = new StringBuilder();
//            string disp = helper.DisplayFor(expression).ToString();
//            if ( !string.IsNullOrEmpty(disp))
//            {
//                html.AppendLine(helper.DisplayNameFor(expression).ToString());
//                html.AppendLine(disp);
//            }
//            return MvcHtmlString.Create(html.ToString());
//        }
//    }
//}

namespace GoTravelABit2.Models
{
    enum TripItemType { Travel = 1, Hotel = 2, Other = 6 }

    partial class TripItem
    {
        public string TypeName => ((TripItemType)Type).ToString();

    }
}

namespace GoTravelABit2.Models

{
    public partial class TripItem
    {

        public static Dictionary<int, string> TripItemVessels = new Dictionary<int, string>
        {
        {0, "Unknown" },
        {1, "Plane" },
        {2, "Car" },
        {3, "Ship" },
        {4, "Public Transport" },
        {5, "Other" },

        };

        public string VesselName => TripItemVessels[this.Wessel ?? 0];

    }

}

namespace GoTravelABit2.Controllers
{
    //public class Riik
    //{
    //    public string name { get; set; }
    //    //public string alpha2Code { get; set; } // saab panna riigikoodi (nt. EE)
    //}

    public class TripItemsController : Controller
    {

        //static List<string> Riigid
        //    => new List<string>

        //    { "Estonia", "Latvia", "Lithuania" };

        //    static List<Riik> Riigid2
        //{
        //    get
        //    {
        //        WebRequest wr = WebRequest.Create("https://restcountries.eu/rest/v2/all");
        //        HttpWebResponse resp = (HttpWebResponse)wr.GetResponse();
        //        Stream str = resp.GetResponseStream();
        //        StreamReader sr = new StreamReader(str);
        //        string vastus = sr.ReadToEnd();
        //        return JsonConvert.DeserializeObject<List<Riik>>(vastus);
        //    }
        //}
        private ReisidEntities db = new ReisidEntities();

        [OutputCache(Duration = 3600, VaryByParam = "id")]
        public ActionResult Pdf(int? id)
        {
            if (id == 0) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var c = db.Files.Find(id.Value);
            if (c == null) return HttpNotFound();

            return File(c.Content.ToArray(), c.ContentType);
        }

        public ActionResult Content(int? id)
        {
            if (id.HasValue)
            {
                Models.File file = db.Files.Find(id.Value);
                if (file != null)
                {
                    return File(file.Content, file.ContentType);
                }
            }
            return HttpNotFound();

        }


        // GET: TripItems

        public ActionResult Index(int? id)
        {

            Trip trip = db.Trips.Find(id);
            if (trip == null) return HttpNotFound();

            var tripitems = db.TripItems.Include(t => t.Trip).Where(t => t.TripId == trip.Id);

            return View(tripitems.ToList());
        }

        // GET: TripItems/Details/5
        public ActionResult Details(int? Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TripItem tripItem = db.TripItems.Find(Id);
            if (tripItem == null)
            {
                return HttpNotFound();
            }
            return View(tripItem);
        }

        //GET: TripItems/Create
        public ActionResult Create(int id, int type)
        {
            Trip trip = db.Trips.Find(id);
            if (trip == null) return HttpNotFound();
            int nr = (trip.TripItems.LastOrDefault()?.Nr ?? 0) + 1;

            ViewBag.Wessel = new SelectList(TripItem.TripItemVessels, "Key", "Value", null);

            return View(new TripItem { TripId = id, Type = type, Nr = nr });

        }


        // POST: TripItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TripId,Nr,Date,Prize,Type,Wessel,Location,ToLocation,Hotel,Duration,Name,Desscription,Comment,CheckInDate,CheckOutDate,StartTime")] TripItem tripItem
            , HttpPostedFileBase file
            )
        {
            Trip trip = db.Trips.Find(tripItem.TripId);
            bool valid = trip != null ?

                (!tripItem.CheckInDate.HasValue || !tripItem.CheckOutDate.HasValue || tripItem.CheckInDate <= tripItem.CheckOutDate)
                && 
                (!tripItem.CheckInDate.HasValue || !trip.Start.HasValue || tripItem.CheckInDate >= trip.Start) 
                && 
                (!tripItem.CheckOutDate.HasValue || !trip.End.HasValue || tripItem.CheckOutDate <= trip.End)
                &&
                (!tripItem.Date.HasValue || !trip.Start.HasValue || tripItem.Date >= trip.Start)
                &&
                (!tripItem.Date.HasValue || !trip.End.HasValue || tripItem.Date <= trip.End)

                : false;
            ViewBag.TripItemDateError = "Date(s) does not fall into trip date range";


            if (ModelState.IsValid && valid)
            {

                
                db.TripItems.Add(tripItem);
                db.SaveChanges();

                
                if (file != null && file.ContentLength > 0)
                {

                    using (BinaryReader br = new BinaryReader(file.InputStream))
                    {
                        byte[] buff = br.ReadBytes(file.ContentLength);
                        Models.File f = new Models.File { Content = buff, Name = tripItem.Name, ContentType = file.ContentType, FileName = file.FileName.Split('\\').Last() };

                        db.Files.Add(f);
                        db.SaveChanges();
                        tripItem.Files.Add(f);
                        db.SaveChanges();

                    }
                }

                return RedirectToAction("Details", "Trips", new { id = tripItem.TripId });
            }
          
            ViewBag.Wessel = new SelectList(TripItem.TripItemVessels, "Key", "Value", null);
            return View(tripItem);
        }



        // GET: TripItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TripItem tripItem = db.TripItems.Find(id);
            if (tripItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.Wessel = new SelectList(TripItem.TripItemVessels, "Key", "Value", null);
            return View(tripItem);
        }


        // POST: TripItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TripId,Nr,Date,Prize,Type,Wessel,Location,ToLocation,Hotel,Duration,Name,Desscription,Comment,CheckInDate,CheckOutDate,StartTime")] TripItem tripItem
            , HttpPostedFileBase file
            )
        {

            Trip trip = db.Trips.Find(tripItem.TripId);
            bool valid = trip != null ?

                (!tripItem.CheckInDate.HasValue || !tripItem.CheckOutDate.HasValue || tripItem.CheckInDate <= tripItem.CheckOutDate)
                &&
                (!tripItem.CheckInDate.HasValue || !trip.Start.HasValue || tripItem.CheckInDate >= trip.Start)
                &&
                (!tripItem.CheckOutDate.HasValue || !trip.End.HasValue || tripItem.CheckOutDate <= trip.End)
                &&
                (!tripItem.Date.HasValue || !trip.Start.HasValue || tripItem.Date >= trip.Start)
                &&
                (!tripItem.Date.HasValue || !trip.End.HasValue || tripItem.Date <= trip.End)

                : false;

            ViewBag.TripItemDateError = "Date(s) does not fall into trip date range";



            if (ModelState.IsValid && valid)
            {
                db.Entry(tripItem).State = EntityState.Modified;
                db.SaveChanges();

                if (file != null && file.ContentLength > 0)
                {

                    using (BinaryReader br = new BinaryReader(file.InputStream))
                    {
                        byte[] buff = br.ReadBytes(file.ContentLength);
                        Models.File f = new Models.File { Content = buff, Name = tripItem.Name, ContentType = file.ContentType, FileName = file.FileName.Split('\\').Last() };

                        db.Files.Add(f);
                        db.SaveChanges();
                        tripItem.Files.Add(f);
                        db.SaveChanges();

                    }
                }

                return RedirectToAction("Details", "Trips", new { id = tripItem.TripId });
            }

            db.SaveChanges();
            return View(tripItem);


        }

        public ActionResult DeleteFile(int id, int tripitem)
        {

GoTravelABit2/Views/TripItems/Details.cshtml
@model GoTravelABit2.Models.TripItem

<br />
<img src="~/Content/Website Images/itemdetails.png" style="width:95%; height:auto; border-radius:8px; height:auto;" alt="My Trips">


<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Trip Id")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TripId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nr)
        </dd>

        <dt>
            @if (Model.Date != null)
            {
                @Html.DisplayNameFor(model => model.Date)
            }
        </dt>

        <dd>
            @if (Model.Date != null)
            {
                @Html.DisplayFor(model => model.Date)
            }
        </dd>

        <dt>
            @if (Model.StartTime != null)
            {
                @Html.DisplayName("Start Time")
            }
        </dt>

        <dd>
            @if (Model.StartTime != null)
            {
                @Html.DisplayFor(model => model.StartTime)
            }
        </dd>

        <dt>
            @if (Model.Prize != null)
            {
                @Html.DisplayName("Price (€)")
            }
        </dt>

        <dd>
            @if (Model.Prize != null)
            {
                @Html.DisplayFor(model => model.Prize)
            }
        </dd>

        @*<dt>
                @Html.DisplayNameFor(model => model.Type)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Type)
            </dd>*@
        @Html.HiddenFor(model => model.Type)

        <dt>
            @if (Model.Wessel != null)
            {
                @Html.DisplayName("Transport")
            }
        </dt>

        <dd>
            @if (Model.Wessel != null)
            {
                @Html.DisplayFor(model => model.VesselName)
            }
        </dd>

        <dt>
            @if (Model.Location != null)
            {
                @Html.DisplayName("From")
            }
        </dt>

        <dd>
            @if (Model.Location != null)
            {
                @Html.DisplayFor(model => model.Location)
            }
        </dd>

        <dt>
            @if (Model.ToLocation != null)
            {
                @Html.DisplayName("To")
            }
        </dt>

        <dd>
            @if (Model.ToLocation != null)
            {
                @Html.DisplayFor(model => model.ToLocation)
            }
        </dd>

        <dt>
            @if (Model.Hotel != null)
            {
                @Html.DisplayNameFor(model => model.Hotel)
            }
        </dt>

        <dd>
            @if (Model.Hotel != null)
            {
                @Html.DisplayFor(model => model.Hotel)
            }
        </dd>

        <dt>
            @if (Model.CheckInDate != null)
            {
                @Html.DisplayName("Check-In Date")
            }
        </dt>

        <dd>
            @if (Model.CheckInDate != null)
            {
                @Html.DisplayFor(model => model.CheckInDate)
            }
        </dd>

        <dt>
            @if (Model.CheckOutDate != null)
            {
                @Html.DisplayName("Check-Out Date")
            }
        </dt>

        <dd>
            @if (Model.CheckOutDate != null)
            {
                @Html.DisplayFor(model => model.CheckOutDate)
            }
        </dd>

        @*<dt>
            @if (Model.Duration != null)
        {
            @Html.DisplayNameFor(model => model.Duration)
    }
        </dt>*@

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @if (Model.Name != null)
            {
                @Html.DisplayNameFor(model => model.Name)
            }
        </dt>

        <dd>
            @if (Model.Name != null)
            {
                @Html.DisplayFor(model => model.Name)
            }
        </dd>

        <dt>
            @if (Model.Desscription != null)
            {
                @Html.DisplayName("Description")
            }
        </dt>

        <dd>
            @if (Model.Desscription != null)
            {
                @Html.DisplayFor(model => model.Desscription)
            }
        </dd>

        <dt>
            @if (Model.Comment != null)
            {
                @Html.DisplayNameFor(model => model.Comment)
            }
        </dt>

        <dd>
            @if (Model.Comment != null)
            {
                @Html.DisplayFor(model => model.Comment)
            }
        </dd>



    </dl>
</div>


<div>
    <ul>
        @foreach (var x in Model.Files.Select(f => new { f.Id, f.FileName, f.ContentType }))
        {


            if (x.ContentType.Contains("image"))
            {
                <li>

                    <img src="@Url.Action("Content", "Files", new { id = x.Id })" height="100" id="picture" />

                </li>
                <br />
            }
            else
            {

                <li>  @Html.ActionLink(x.FileName, "Content", "Files", new { id = x.Id }, null)  </li>
                <br />

            }


        }
    </ul>
</div>


<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, htmlAttributes: new { @class = "nupp"})
    @Html.ActionLink("Back to List", "Details", "Trips", null, htmlAttributes: new { @class = "nupp", id = Model.TripId })
</p>

GoTravelABit2/Views/TripItems/Edit.cshtml
@model GoTravelABit2.Models.TripItem

<br />
<img src="~/Content/Website Images/edititem.png" style="width:95%; height:auto; border-radius:8px; height:auto;" alt="Edit Item">
<br />
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angulavr.min.js"></script>


<div>
    <ul>
        @foreach (var x in Model.Files.Select(f => new { f.Id, f.FileName, f.ContentType }))
        {

            if (x.ContentType.Contains("image"))
            {
                <li>

                    <img src="@Url.Action("Content", "Files", new { id = x.Id })" height="100" id="picture" /> ||
                    @Html.ActionLink("Remove File", "DeleteFile", new { id = x.Id, tripitem = Model.Id })

                </li>
                <br />
            }
            else
            {
                <li>

                    @Html.ActionLink(x.FileName, "Content", "Files", new { id = x.Id }, null) ||
                    @Html.ActionLink("Remove File", "DeleteFile", new { id = x.Id, tripitem = Model.Id })

                </li>
                <br />
            }

        }
    </ul>
</div>


@using (Html.BeginForm("Edit", "TripItems", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @switch (Model.Type)
        {
            case 1:
                <h3>Where are you going?</h3>
                break;
            case 2:
                <h3>Where are you staying?</h3>
                break;
            case 6:
                <h3>Activities</h3>
                break;
        }

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <p class="text-danger">@ViewBag.TripItemDateError</p>


        @*@Html.HiddenFor(model => model.Id)*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.TripId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TripId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TripId, "", new { @class = "text-danger" })
                </div>
            </div>*@
        @Html.HiddenFor(model => model.TripId)

        @*<div class="form-group">
                @Html.LabelFor(model => model.Nr, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nr, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nr, "", new { @class = "text-danger" })
                </div>
            </div>*@
        @Html.HiddenFor(model => model.Nr)

        @*<div class="form-group">
                @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control datepicker" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>*@
        @Html.HiddenFor(model => model.Type)

        <div class="form-group">
            @Html.Label("Item Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Location", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>


        @switch (Model.Type)

        {
            case 1:

                <div class="form-group">
                    @Html.Label("To Location", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ToLocation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ToLocation, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control datepicker" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Transport", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Wessel", null, "Choose transport", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Wessel, "", new { @class = "text-danger" })
                    </div>
                </div>


                break;

            case 2:

                <div class="form-group">
                    @Html.Label("Hotel Name", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Hotel, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Hotel, "", new { @class = "text-danger" })
                    </div>
                </div>

            <div class="form-group">
                @Html.Label("Check-In Date", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CheckInDate, new { htmlAttributes = new { @class = "form-control datepicker", id = "start", @type = "string", @onchange = "change('start', 'stop', 'delta')" } })
                    @Html.ValidationMessageFor(model => model.CheckInDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Check-Out Date", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CheckOutDate, new { htmlAttributes = new { @class = "form-control datepicker", id = "stop", @type = "string", @onchange = "change('start', 'stop', 'delta')" } })
                    @Html.ValidationMessageFor(model => model.CheckOutDate, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                @Html.Label("No of Nights", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control", id = "delta", @disabled = "disabled" } })
                    @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
                </div>
            </div>*@
            @Html.HiddenFor(model => model.Duration)

            @*<script src="~/Scripts/jquery-1.10.2.js"></script>
            <script>
                function change(sta, sto, del) {
                    var start = dateparse($("#" + sta).val());
                    var stop = dateparse($("#" + sto).val());
                    //daysOfMonths = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
                    $("#" + del).val(parseInt((stop - start) / (3600 * 24000)));
                }
                function dateparse(str) {
                    var d = Date.parse(str);
                    if (d) return d;
                    var parts = str.split('.');
                    return new Date(parts[2], parts[1], parts[0]);
                }
            </script>*@

                break;
            case 6:

                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control datepicker" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Start Time", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Description", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Desscription, new { htmlAttributes = new { @class = "form-control", @placeholder = "What's the exact plan?" } })
                        @Html.ValidationMessageFor(model => model.Desscription, "", new { @class = "text-danger" })
                    </div>
                </div>
                break;
        }


        <div class="form-group">
            @Html.Label("Price (€)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prize, new { htmlAttributes = new { @class = "form-control", @placeholder = "Price in Euros (€)" } })
                @Html.ValidationMessageFor(model => model.Prize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Comment, new { style = "width:400px; height:100px", @class = "form-control", @placeholder = "Anything else to add?" })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label for="file" class="control-label col-md-2" style="margin-left:38px">Add file:</label>
                <input type="file" name="file" id="file" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-nupp" />
            </div>
        </div>
    </div>
}


@Html.ActionLink("Back to List", "Details", "Trips", null, new { @class = "nupp", id = Model.TripId })

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#pilt').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $(document).ready(function () {
        $("#file").change(function () {
            readURL(this);
        });
    });

</script>